"""Build sample-data.js for the M3a mockup from the captured responses in sample/.

Everything under sample/*.json is real simulator output, copied into the page unchanged
apart from one added key per exchange, "_provenance": "captured". The hand-made items
below are appended after the capture's last seq and carry "_provenance": "synthetic"
plus a "_synthetic_note" saying why each exists. The page reads those two keys; the
API never sends them.

Run from anywhere:  python3 docs/mockups/m3a-dashboard/build_sample_data.py
"""

from __future__ import annotations

import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
SAMPLE = HERE / "sample"


def load(name: str) -> dict:
    return json.loads((SAMPLE / f"{name}.json").read_text())


def synthetic(note: str, **event: object) -> dict:
    return {"type": "exchange", **event, "_provenance": "synthetic", "_synthetic_note": note}


def build() -> dict:
    exchanges = load("exchanges")
    events = [dict(e, _provenance="captured") for e in exchanges["events"]]
    last = events[-1]["seq"]  # 29 in the committed capture

    long_response = bytes([0x59, 0x02, 0xFF]) + bytes((i * 7) & 0xFF for i in range(597))
    tail = [
        synthetic(
            "Hand-made. 'unrouted' is not reachable in v1 as built (0010 §4.4); this row "
            "exists only so its style can be reviewed.",
            seq=last + 1, t="2026-09-28T20:15:26.102Z", ecu=None, endpoint=None,
            rx_id="0x7e5", tx_id=None, functional=False,
            request="22f190", request_len=3, request_truncated=False,
            response=None, response_len=0, response_truncated=False,
            outcome="unrouted", error=None, dispatch_us=212, summary="service 0x22",
        ),
        synthetic(
            "Hand-made. The capture had no dispatcher exception; this shows the 'error' row.",
            seq=last + 2, t="2026-09-28T20:15:26.410Z", ecu="engine",
            endpoint="engine.uds_physical", rx_id="0x7e1", tx_id="0x7e9", functional=False,
            request="1902ff", request_len=3, request_truncated=False,
            response=None, response_len=0, response_truncated=False,
            outcome="error", error="KeyError", dispatch_us=388,
            summary="UDS 19 — ReadDTCInformation",
        ),
        # seq last+3 .. last+6 are deliberately absent: the gap, explained by `dropped`.
        synthetic(
            "Hand-made. A 600-byte response, retained to 512 bytes, to show the truncation "
            "flag. The profile cannot produce a reply this long.",
            seq=last + 7, t="2026-09-28T20:15:27.953Z", ecu="engine",
            endpoint="engine.uds_physical", rx_id="0x7e1", tx_id="0x7e9", functional=False,
            request="1902ff", request_len=3, request_truncated=False,
            response=long_response[:512].hex(), response_len=len(long_response),
            response_truncated=True, outcome="responded", error=None, dispatch_us=517,
            summary="UDS 19 — ReadDTCInformation",
        ),
        synthetic(
            "Hand-made. The encode_failed fallback event of 0010 §5: only seq, outcome "
            "and error are present.",
            seq=last + 8, outcome="responded", error="encode_failed",
        ),
    ]
    dropped = {
        "type": "dropped", "handoff_dropped": 0, "client_dropped": 4, "forced_disconnects": 0,
        "_provenance": "synthetic",
        "_synthetic_note": "Hand-made. Explains the hand-made gap; the capture had no WebSocket client.",
        "_after_seq": last + 2,
    }
    return {
        "meta": json.loads((SAMPLE / "capture-meta.json").read_text()),
        "status": load("status"),
        "vehicle": load("vehicle"),
        "dtcs": load("dtcs"),
        "ecus": load("ecus"),
        "exchanges": {
            "watermark": exchanges["watermark"],
            "oldest_seq": exchanges["oldest_seq"],
            "gap": exchanges["gap"],
            "events": events + tail,
        },
        "dropped": dropped,
        "captured_last_seq": last,
    }


def main() -> None:
    data = build()
    body = json.dumps(data, indent=1, ensure_ascii=False)
    (HERE / "sample-data.js").write_text(
        "// Generated by build_sample_data.py from sample/*.json. Do not edit by hand.\n"
        "// Captured items are real simulator output replayed statically; items with\n"
        "// \"_provenance\": \"synthetic\" are hand-made and say why.\n"
        f"window.ECU_SAMPLE = {body};\n"
    )


if __name__ == "__main__":
    main()
